services:
  postgres:
    image: postgres:15
    container_name: traningsetapp-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traningsetapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: traningsetapp-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/traningsetapp
    depends_on:
      - postgres
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
